// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxkljzytssofphkedakk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4a2xqenl0c3NvZnBoa2VkYWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjMwNzIsImV4cCI6MjA2OTUzOTA3Mn0.POEDMacn5rMVSZWYBQp3bbQvFRcFzMHXOjo6hLgQyzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});